version: "3.9"

services:
  web:
    build: .
    container_name: mi_sistema
    ports:
      - "8085:80"
      - "8443:443"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - red_interna
    environment:
      DB_HOST: db
      DB_USER: proyutu
      DB_PASSWORD: 12345678
      DB_NAME: proyutu

  db:
    image: mariadb:10.6
    container_name: mi_basedatos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proyutu
      MYSQL_USER: proyutu
      MYSQL_PASSWORD: 12345678
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - db_data:/var/lib/mysql
    networks:
      - red_interna

networks:
  red_interna:

volumes:
  db_data:
